version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
        NEXT_PUBLIC_PAYLOAD_API_URL: ${NEXT_PUBLIC_PAYLOAD_API_URL}
        NEXT_PUBLIC_PAYLOAD_API_TOKEN: ${NEXT_PUBLIC_PAYLOAD_API_TOKEN}
        NEXT_PUBLIC_CMS_URL: ${NEXT_PUBLIC_CMS_URL}
        NEXT_PUBLIC_TELEGRAM_BOT_TOKEN: ${NEXT_PUBLIC_TELEGRAM_BOT_TOKEN}
        NEXT_PUBLIC_TELEGRAM_CHAT_ID: ${NEXT_PUBLIC_TELEGRAM_CHAT_ID}
        NEXT_PUBLIC_EMAIL_HOST: ${NEXT_PUBLIC_EMAIL_HOST}
        NEXT_PUBLIC_EMAIL_PORT: ${NEXT_PUBLIC_EMAIL_PORT}
        NEXT_PUBLIC_EMAIL_USER: ${NEXT_PUBLIC_EMAIL_USER}
        NEXT_PUBLIC_EMAIL_PASS: ${NEXT_PUBLIC_EMAIL_PASS}
        NEXT_PUBLIC_EMAIL_FROM: ${NEXT_PUBLIC_EMAIL_FROM}
        NEXT_PUBLIC_EMAIL_TO: ${NEXT_PUBLIC_EMAIL_TO}
    image: hett-frontend:${TAG}
    restart: unless-stopped
    ports:
      - "3008:3001"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - NEXT_PUBLIC_PAYLOAD_API_URL=${NEXT_PUBLIC_PAYLOAD_API_URL}
      - NEXT_PUBLIC_PAYLOAD_API_TOKEN=${NEXT_PUBLIC_PAYLOAD_API_TOKEN}
      - NEXT_PUBLIC_CMS_URL=${NEXT_PUBLIC_CMS_URL}
      - NEXT_PUBLIC_TELEGRAM_BOT_TOKEN=${NEXT_PUBLIC_TELEGRAM_BOT_TOKEN}
      - NEXT_PUBLIC_TELEGRAM_CHAT_ID=${NEXT_PUBLIC_TELEGRAM_CHAT_ID}
      - NEXT_PUBLIC_EMAIL_HOST=${NEXT_PUBLIC_EMAIL_HOST}
      - NEXT_PUBLIC_EMAIL_PORT=${NEXT_PUBLIC_EMAIL_PORT}
      - NEXT_PUBLIC_EMAIL_USER=${NEXT_PUBLIC_EMAIL_USER}
      - NEXT_PUBLIC_EMAIL_PASS=${NEXT_PUBLIC_EMAIL_PASS}
      - NEXT_PUBLIC_EMAIL_FROM=${NEXT_PUBLIC_EMAIL_FROM}
      - NEXT_PUBLIC_EMAIL_TO=${NEXT_PUBLIC_EMAIL_TO}
    networks:
      - hett-network

networks:
  hett-network:
    driver: bridge 