version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    # При необходимости можно добавить тома для хранения данных
    # volumes:
    #   - ./public:/app/public
